version: "3"

tasks:
  verify:
    desc: "Verify toolchain + venv + env + infra"
    cmds:
      - sh scripts/ops/verify.sh

  run:
    desc: "Run API server"
    cmds:
      - sh scripts/ops/ready.sh

  dev:
    desc: "Verify + run"
    cmds:
      - task: verify
      - task: run

  seed:
    desc: "Reset and seed data (canonical)"
    cmds:
      - uv run python scripts/ops/seed_db.py

  up:
    desc: "Apply migrations via python module"
    cmds:
      - uv run python -m alembic upgrade head

  migrate:
    desc: "Generate migrations via python module"
    cmds:
      - uv run python -m alembic revision --autogenerate -m "{{.CLI_ARGS}}"
