"""check for drift

Revision ID: 09046051e190
Revises: a55c7b1ad9e9
Create Date: 2026-02-24 13:08:32.628143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09046051e190'
down_revision: Union[str, Sequence[str], None] = 'a55c7b1ad9e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_index(op.f('ix_reservations_dining_room_id'), 'reservations', ['dining_room_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_dining_room_id'), table_name='reservations')
    # ### end Alembic commands ###
