"""create seat_assignments

Revision ID: 5f2b79ac396c
Revises: 7dbeedae6d04
Create Date: 2026-02-20 20:44:15.733712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2b79ac396c'
down_revision: Union[str, Sequence[str], None] = '7dbeedae6d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seat_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_assignments_reservation_id'), 'seat_assignments', ['reservation_id'], unique=True)
    op.create_index(op.f('ix_seat_assignments_table_id'), 'seat_assignments', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seat_assignments_table_id'), table_name='seat_assignments')
    op.drop_index(op.f('ix_seat_assignments_reservation_id'), table_name='seat_assignments')
    op.drop_table('seat_assignments')
    # ### end Alembic commands ###
