"""create messages table

Revision ID: 02b291c4315a
Revises: 3de4a3bd5ffd
Create Date: 2026-02-20 17:36:14.975082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b291c4315a'
down_revision: Union[str, Sequence[str], None] = '3de4a3bd5ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_messages_attendee_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.create_index(op.f('ix_messages_sender_user_id'), 'messages', ['sender_user_id'], unique=False)
    op.drop_constraint(op.f('messages_attendee_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_user_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('messages', 'attendee_id')
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('attendee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_user_id_fkey'), 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messages_attendee_id_fkey'), 'messages', 'reservation_attendees', ['attendee_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_messages_sender_user_id'), table_name='messages')
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_messages_attendee_id'), 'messages', ['attendee_id'], unique=False)
    op.drop_column('messages', 'sender_user_id')
    # ### end Alembic commands ###
