"""create members table

Revision ID: c677edcaa079
Revises: 6aa0231f8798
Create Date: 2026-02-20 11:54:58.734116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c677edcaa079'
down_revision: Union[str, Sequence[str], None] = '6aa0231f8798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=True),
    sa.Column('dietary_restrictions', postgresql.ARRAY(postgresql.ENUM('dairy_free', 'egg_free', 'fish_allergy', 'gluten_free', 'halal', 'kosher', 'nut_allergy', 'peanut_allergy', 'sesame_allergy', 'shellfish_allergy', 'soy_free', 'vegan', 'vegetarian', name='dietary_restriction_enum')), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_user_id'), 'members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_user_id'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
