"""add category to menu_items

Revision ID: 1deddf9967eb
Revises: b04a2986fe90
Create Date: 2026-02-28 20:33:41.201707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1deddf9967eb'
down_revision: Union[str, Sequence[str], None] = 'b04a2986fe90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('category', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_menu_items_category'), 'menu_items', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_items_category'), table_name='menu_items')
    op.drop_column('menu_items', 'category')
    # ### end Alembic commands ###
